name: Publish Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Install DocFX
      run: dotnet tool install -g docfx
    
    - name: Build Documentation
      run: |
        docfx init -q
        docfx build
    
    - name: Create .nojekyll file
      run: touch _site/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GG }}
        publish_dir: ./_site
        force_orphan: true 